### ISSUE TITLE
Move local benchmark script to scripts folder and add minimal documentation

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/SoK#34]

**Comment by AlexanderViand** [comment]
It seems like the move broke the script a tiny bit
`./execute_benchmark_locally.sh: line 80: cd: SEAL: No such file or directory`

**Comment by pjattke** [comment]
I already noticed it, thanks! It's fixed in 328443f91d4489f0c80405ba5a6794b90ab646fe.
