### ISSUE TITLE
Check why plotting failed in benchmark task

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/SoK#39]
Look into the last GA benchmark run and check why plotting failed, see the log here: https://github.com/MarbleHE/SoK/runs/1479985694?check_suite_focus=true

**Comment by AlexanderViand** [comment]
I've changed some names of the SEAL-BFV-cardio benchmarks, and while the plotting script can tolerate some failures, after too many some variables won't be initalized in plot_cardio.py 

There might be other reasons, too, since plotting also failed before...

**Comment by pjattke** [comment]
Locally, the plotting seems to be working fine now. Later, when the still [running benchmark task](https://github.com/MarbleHE/SoK/runs/1480017130?check_suite_focus=true) finished, I will check if plotting didn't work there.

**Comment by pjattke** [comment]
This is not solved yet. See the latest GA run here: https://github.com/MarbleHE/SoK/runs/1481175847?check_suite_focus=true

- [ ] Add packages `texlive-latex-extra`, `texlive-fonts-recommended` and `dvipng` to github runner
- [ ] Create separate (dependent) Github action for plotting to make generating visualization easier and allow manual premature plots generation
    - This is described here in more detail: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run
