### ISSUE TITLE
Wiki images broken - HTTP 406 errors

### ISSUE THREAD

**Issue by gitcnd** [MarbleHE/SoK#44]
The Wiki here: https://github.com/MarbleHE/SoK/wiki

Attempts to embed these files:-

https://github.com/MarbleHE/SoK/wiki/docs/tableI.png

https://github.com/MarbleHE/SoK/wiki/docs/tableII.png

Both of which are broken images (HTTP/406)

**Comment by gitcnd** [comment]
These might be better links? I'm not sure:-

https://github.com/MarbleHE/SoK/raw/master/docs/tableI.png
https://github.com/MarbleHE/SoK/raw/master/docs/tableII.png

**Comment by AlexanderViand** [comment]
Thanks! The original links apparently work in in-repo readmes but not in the wiki, so I've swapped them with your suggestion :)
