### ISSUE TITLE
SoK Abbreviation

### ISSUE THREAD

**Issue by macknight** [MarbleHE/SoK#56]
May I know what SoK stands for?

BR

**Comment by AlexanderViand** [comment]
Right, the readme could probably be a lot clearer. SoK stands for "Systematization of Knowledge", which is a special type of paper at some major Computer Science conferences. This repository includes the code we used to generate the results in our paper [SoK: Fully Homomorphic Encryption Compilers](https://arxiv.org/abs/2101.07078)

**Comment by macknight** [comment]
Cool, thank you for your reply.
